phrase = "Don't panic!"
plist = list(phrase)
print(phrase)
print(plist)
plist.remove("D")
plist.remove("'")
plist.insert(2, " ")
plist.remove("i")
plist.remove("c")
g = plist.pop(6)
plist.insert(5, g)
plist.pop(4)
plist.pop(6)
plist.pop()
new_phrase = ''.join(plist)
print(plist)
print(new_phrase)
